@url_dev=http://localhost:3056/v1/api/

### signup
POST {{{{url_dev}}}}/shop/signup
Content-Type: application/json
x-api-key: acjbhbhjnjknlnjbahb

{
    "name": "Shop",
    "email": "test@gmail.com",
    "password": "abc123"
}